# pip install pre-commit
# pre-commit install
# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: debug-statements
    -   id: end-of-file-fixer
        types: [python, toml]
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.264'
    hooks:
      - id: ruff
        name: ruff - lint python code
        args: [--fix]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'
    hooks:
    -   id: mypy
        name: mypy - static type checker
        args: [--config-file, pyproject.toml]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        name: black - format python files
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort - sort python includes
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
        name: pyupgrade - modernize python code
